
// Generated by https://quicktype.io

export interface JikanPictures {
    request_hash:         string;
    request_cached:       boolean;
    request_cache_expiry: number;
    pictures:             Picture[];
}

export interface Picture {
    large: string;
    small: string;
}


// Generated by https://quicktype.io

export interface JikanEpisodes {
    request_hash:         string;
    request_cached:       boolean;
    request_cache_expiry: number;
    episodes_last_page:   number;
    episodes:             Episode[];
}

export interface Episode {
    episode_id:     number;
    title:          string;
    title_japanese: null | string;
    title_romanji:  null | string;
    aired:          null | string;
    filler:         boolean;
    recap:          boolean;
    video_url:      string;
    forum_url:      string;
}




// Generated by https://quicktype.io

export interface JikanStats {
    request_hash:         string;
    request_cached:       boolean;
    request_cache_expiry: number;
    watching:             number;
    completed:            number;
    on_hold:              number;
    dropped:              number;
    plan_to_watch:        number;
    total:                number;
    scores:               { [key: string]: Score };
}

export interface Score {
    votes:      number;
    percentage: number;
}



// Generated by https://quicktype.io

export interface JikanQuery {
    request_hash:         string;
    request_cached:       boolean;
    request_cache_expiry: number;
    results:              Result[];
    last_page:            number;
}

export interface Result {
    mal_id:     number;
    url:        string;
    image_url:  string;
    title:      string;
    airing:     boolean;
    synopsis:   string;
    type:       Type;
    episodes:   number;
    score:      number;
    start_date: string;
    end_date:   null | string;
    members:    number;
    rated:      Rated | null;
}

export enum Rated {
    G = "G",
    PG = "PG",
    PG13 = "PG-13",
    R = "R",
    RatedR = "R+",
    Rx = "Rx",
}

export enum Type {
    Movie = "Movie",
    Music = "Music",
    Ona = "ONA",
    Ova = "OVA",
    Special = "Special",
    Tv = "TV",
}
