// Generated by https://quicktype.io

export interface JikanAnime {
    request_hash:         string;
    request_cached:       boolean;
    request_cache_expiry: number;
    mal_id:               number;
    url:                  string;
    image_url:            string;
    trailer_url:          string;
    title:                string;
    title_english:        string;
    title_japanese:       string;
    title_synonyms:       string[];
    type:                 string;
    source:               string;
    episodes:             null;
    status:               string;
    airing:               boolean;
    aired:                Aired;
    duration:             string;
    rating:               string;
    score:                number;
    scored_by:            number;
    rank:                 number;
    popularity:           number;
    members:              number;
    favorites:            number;
    synopsis:             string;
    background:           null;
    premiered:            string;
    broadcast:            string;
    related:              Related;
    producers:            Demographic[];
    licensors:            any[];
    studios:              Demographic[];
    genres:               Demographic[];
    explicit_genres:      any[];
    demographics:         Demographic[];
    themes:               Demographic[];
    opening_themes:       string[];
    ending_themes:        string[];
    external_links:       ExternalLink[];
}

export interface Aired {
    from:   string;
    to:     null;
    prop:   Prop;
    string: string;
}

export interface Prop {
    from: From;
    to:   From;
}

export interface From {
    day:   number | null;
    month: number | null;
    year:  number | null;
}

export interface Demographic {
    mal_id: number;
    type:   string;
    name:   string;
    url:    string;
}

export interface ExternalLink {
    name: string;
    url:  string;
}

export interface Related {
    Adaptation: Demographic[];
}


// Generated by https://quicktype.io

export interface JikanPictures {
    request_hash:         string;
    request_cached:       boolean;
    request_cache_expiry: number;
    pictures:             Picture[];
}

export interface Picture {
    large: string;
    small: string;
}


// Generated by https://quicktype.io

export interface JikanEpisodes {
    request_hash:         string;
    request_cached:       boolean;
    request_cache_expiry: number;
    episodes_last_page:   number;
    episodes:             Episode[];
}

export interface Episode {
    episode_id:     number;
    title:          string;
    title_japanese: null | string;
    title_romanji:  null | string;
    aired:          null | string;
    filler:         boolean;
    recap:          boolean;
    video_url:      string;
    forum_url:      string;
}




// Generated by https://quicktype.io

export interface JikanStats {
    request_hash:         string;
    request_cached:       boolean;
    request_cache_expiry: number;
    watching:             number;
    completed:            number;
    on_hold:              number;
    dropped:              number;
    plan_to_watch:        number;
    total:                number;
    scores:               { [key: string]: Score };
}

export interface Score {
    votes:      number;
    percentage: number;
}



// Generated by https://quicktype.io

export interface JikanQuery {
    request_hash:         string;
    request_cached:       boolean;
    request_cache_expiry: number;
    results:              Result[];
    last_page:            number;
}

export interface Result {
    mal_id:     number;
    url:        string;
    image_url:  string;
    title:      string;
    airing:     boolean;
    synopsis:   string;
    type:       Type;
    episodes:   number;
    score:      number;
    start_date: string;
    end_date:   null | string;
    members:    number;
    rated:      Rated | null;
}

export enum Rated {
    G = "G",
    PG = "PG",
    PG13 = "PG-13",
    R = "R",
    RatedR = "R+",
    Rx = "Rx",
}

export enum Type {
    Movie = "Movie",
    Music = "Music",
    Ona = "ONA",
    Ova = "OVA",
    Special = "Special",
    Tv = "TV",
}
